config/routes.rb
Rails.application.routes.default_url_options[:host] = 'localhost:3000'

Rails.application.routes.draw do
  devise_for :users, controllers: {
  	registrations: "users/registrations"
  }
	root "listings#index"
  resources :listings
end

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" id="trigger" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= image_tag "real-estate-star-128_2.png", height: 50 %> HOMESTAR</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="menu">
      <ul class="nav navbar-nav">
        <li><%= link_to "All Listings", listings_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "New Listing", new_listing_path %></li>
          <% if @listing && @listing.user == current_user %>
            <li><%= link_to "Edit Listing", edit_listing_path(@listing) %></li>
          <% end %>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if !user_signed_in? %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>

        <% if user_signed_in? %>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete%></li>
        <% else %>
          <li><%= link_to "Log In", new_user_session_path%></li>
        <% end %>
      </ul>
       <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>